AllCops:
  Include:
    - Gemfile
    - Guardfile
    - config.ru
    - Rakefile
    - !ruby/regexp /.*\.rake\z/
  Exclude:
    - node_modules/**/*
    - vendor/**/*
  RunRailsCops: true

Documentation:
  Enabled: false

TrailingComma:
  EnforcedStyleForMultiline: comma

HasAndBelongsToMany:
  Enabled: false

AmbiguousRegexpLiteral:
  Exclude:
    - features/**/*_steps.rb
